//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_SEARCH
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public int cmp_id { get; set; }
        public string cmp_name { get; set; }
        public string cmp_email { get; set; }
        public string cmp_phone { get; set; }
        public string cmp_desc { get; set; }
        public string cmp_address { get; set; }
    }
}
