//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_SEARCH
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_application
    {
        public int apply_id { get; set; }
        public int user_id { get; set; }
        public int job_id { get; set; }
        public System.DateTime apply_date { get; set; }
        public string resume { get; set; }
        public string appli_status { get; set; }
    }
}
