//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_SEARCH
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_posting
    {
        public int job_id { get; set; }
        public int cmp_id { get; set; }
        public string job_title { get; set; }
        public string job_desc { get; set; }
        public string location { get; set; }
        public string salary { get; set; }
        public string quali { get; set; }
        public string exp { get; set; }
        public System.DateTime last_date { get; set; }
        public string job_status { get; set; }
    }
}
