//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_SEARCH
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JOB_SEARCHEntities : DbContext
    {
        public JOB_SEARCHEntities()
            : base("name=JOB_SEARCHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<job_application> job_application { get; set; }
        public virtual DbSet<job_posting> job_posting { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<usert> userts { get; set; }
    
        public virtual int sp_cmpreg(Nullable<int> cid, string cna, string cemail, string cphone, string cdesc, string caddr)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var cnaParameter = cna != null ?
                new ObjectParameter("cna", cna) :
                new ObjectParameter("cna", typeof(string));
    
            var cemailParameter = cemail != null ?
                new ObjectParameter("cemail", cemail) :
                new ObjectParameter("cemail", typeof(string));
    
            var cphoneParameter = cphone != null ?
                new ObjectParameter("cphone", cphone) :
                new ObjectParameter("cphone", typeof(string));
    
            var cdescParameter = cdesc != null ?
                new ObjectParameter("cdesc", cdesc) :
                new ObjectParameter("cdesc", typeof(string));
    
            var caddrParameter = caddr != null ?
                new ObjectParameter("caddr", caddr) :
                new ObjectParameter("caddr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_cmpreg", cidParameter, cnaParameter, cemailParameter, cphoneParameter, cdescParameter, caddrParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_countid(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_countid", unaParameter, pwdParameter);
        }
    
        public virtual int sp_jobpost(Nullable<int> cmp_id, string job_title, string job_desc, string location, string salary, string qualification, string experience, Nullable<System.DateTime> last_date, string job_status)
        {
            var cmp_idParameter = cmp_id.HasValue ?
                new ObjectParameter("cmp_id", cmp_id) :
                new ObjectParameter("cmp_id", typeof(int));
    
            var job_titleParameter = job_title != null ?
                new ObjectParameter("job_title", job_title) :
                new ObjectParameter("job_title", typeof(string));
    
            var job_descParameter = job_desc != null ?
                new ObjectParameter("job_desc", job_desc) :
                new ObjectParameter("job_desc", typeof(string));
    
            var locationParameter = location != null ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(string));
    
            var salaryParameter = salary != null ?
                new ObjectParameter("salary", salary) :
                new ObjectParameter("salary", typeof(string));
    
            var qualificationParameter = qualification != null ?
                new ObjectParameter("qualification", qualification) :
                new ObjectParameter("qualification", typeof(string));
    
            var experienceParameter = experience != null ?
                new ObjectParameter("experience", experience) :
                new ObjectParameter("experience", typeof(string));
    
            var last_dateParameter = last_date.HasValue ?
                new ObjectParameter("last_date", last_date) :
                new ObjectParameter("last_date", typeof(System.DateTime));
    
            var job_statusParameter = job_status != null ?
                new ObjectParameter("job_status", job_status) :
                new ObjectParameter("job_status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_jobpost", cmp_idParameter, job_titleParameter, job_descParameter, locationParameter, salaryParameter, qualificationParameter, experienceParameter, last_dateParameter, job_statusParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_loginid(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_loginid", unaParameter, pwdParameter);
        }
    
        public virtual int sp_logininsert(Nullable<int> rid, string una, string pw, string lst)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            var lstParameter = lst != null ?
                new ObjectParameter("lst", lst) :
                new ObjectParameter("lst", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_logininsert", ridParameter, unaParameter, pwParameter, lstParameter);
        }
    
        public virtual ObjectResult<string> sp_logstatus(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_logstatus", unaParameter, pwdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_maxid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_maxid");
        }
    
        public virtual int sp_userreg(Nullable<int> uid, string una, string uph, string uem, string uaddr, string uqua, string uexp, string uskill, string ust)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var uphParameter = uph != null ?
                new ObjectParameter("uph", uph) :
                new ObjectParameter("uph", typeof(string));
    
            var uemParameter = uem != null ?
                new ObjectParameter("uem", uem) :
                new ObjectParameter("uem", typeof(string));
    
            var uaddrParameter = uaddr != null ?
                new ObjectParameter("uaddr", uaddr) :
                new ObjectParameter("uaddr", typeof(string));
    
            var uquaParameter = uqua != null ?
                new ObjectParameter("uqua", uqua) :
                new ObjectParameter("uqua", typeof(string));
    
            var uexpParameter = uexp != null ?
                new ObjectParameter("uexp", uexp) :
                new ObjectParameter("uexp", typeof(string));
    
            var uskillParameter = uskill != null ?
                new ObjectParameter("uskill", uskill) :
                new ObjectParameter("uskill", typeof(string));
    
            var ustParameter = ust != null ?
                new ObjectParameter("ust", ust) :
                new ObjectParameter("ust", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_userreg", uidParameter, unaParameter, uphParameter, uemParameter, uaddrParameter, uquaParameter, uexpParameter, uskillParameter, ustParameter);
        }
    
        public virtual int sp_jobsearch(string qry)
        {
            var qryParameter = qry != null ?
                new ObjectParameter("qry", qry) :
                new ObjectParameter("qry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_jobsearch", qryParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_appliid(Nullable<int> job_id, Nullable<int> user_id)
        {
            var job_idParameter = job_id.HasValue ?
                new ObjectParameter("job_id", job_id) :
                new ObjectParameter("job_id", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_appliid", job_idParameter, user_idParameter);
        }
    
        public virtual int sp_appliinsert(Nullable<int> user_id, Nullable<int> job_id, Nullable<System.DateTime> apply_date, string resume, string appli_status)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var job_idParameter = job_id.HasValue ?
                new ObjectParameter("job_id", job_id) :
                new ObjectParameter("job_id", typeof(int));
    
            var apply_dateParameter = apply_date.HasValue ?
                new ObjectParameter("apply_date", apply_date) :
                new ObjectParameter("apply_date", typeof(System.DateTime));
    
            var resumeParameter = resume != null ?
                new ObjectParameter("resume", resume) :
                new ObjectParameter("resume", typeof(string));
    
            var appli_statusParameter = appli_status != null ?
                new ObjectParameter("appli_status", appli_status) :
                new ObjectParameter("appli_status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_appliinsert", user_idParameter, job_idParameter, apply_dateParameter, resumeParameter, appli_statusParameter);
        }
    }
}
