//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_SEARCH
{
    using System;
    using System.Collections.Generic;
    
    public partial class usert
    {
        public int user_id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string quali { get; set; }
        public string expe { get; set; }
        public string skills { get; set; }
        public string user_status { get; set; }
    }
}
